[book]
authors = ["Seasawher"]
language = "en"
multilingual = false
src = "md"
title = "Lean 99: Ninety-Nine Lean Probelms"
description = "Ninety-Nine Lean coding problems"

[build]
create-missing = false
build-dir = "book"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/lean-ja/lean99"
additional-js = [
  # Add "Run on Lean4 Playground" button to each code block
  "assets/blockPlay.js",

  # Improve search functionality
  "assets/fzf.umd.js",
  "assets/elasticlunr.js"
]