name: run build on current nightly

on:
  schedule:
    - cron: '0 14 1 * *'
  workflow_dispatch:

jobs:
  build:
    name: build periodic nightly
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
          ~/.elan/bin/lean --version
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - name: override elan default
        run: elan override set leanprover/lean4:nightly
      - name: build
        run: lake build
